# Generated by Django 5.2.17 on 2026-09-27 14:39

import mail.models
from django.db import migrations, models


def group_existing_threads(apps, schema_editor):
    """Put existing emails with the same subject (ignoring "Re:") and the same
    people into one thread. The sender's and recipients' copies share the id."""
    Email = apps.get_model("mail", "Email")
    thread_ids = {}
    for email in Email.objects.order_by("timestamp"):
        people = frozenset([email.sender_id, *email.recipients.values_list("id", flat=True)])
        key = (mail.models.normalize_subject(email.subject).lower(), people)
        email.thread_id = thread_ids.setdefault(key, mail.models.new_thread_id())
        email.save(update_fields=["thread_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_attachment_email_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='thread_id',
            field=models.CharField(db_index=True, default=mail.models.new_thread_id, max_length=32),
        ),
        migrations.RunPython(group_existing_threads, migrations.RunPython.noop),
    ]
